# Generated by Django 4.1.2 on 2022-10-12 22:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='img/default.jpg', upload_to='photos/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('is_mvp', models.BooleanField(default=False)),
                ('hire_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('sqrf', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('photo_main', models.ImageField(default='default.jpg', upload_to='photo/%Y/%m/%d/')),
                ('photo1', models.ImageField(blank=True, default='default.jpg', upload_to='photo/%Y/%m/%d/')),
                ('photo2', models.ImageField(blank=True, default='default.jpg', upload_to='photo/%Y/%m/%d/')),
                ('photo3', models.ImageField(blank=True, default='default.jpg', upload_to='photo/%Y/%m/%d/')),
                ('photo4', models.ImageField(blank=True, default='default.jpg', upload_to='photo/%Y/%m/%d/')),
                ('photo5', models.ImageField(blank=True, default='default.jpg', upload_to='photo/%Y/%m/%d/')),
                ('photo6', models.ImageField(blank=True, default='default.jpg', upload_to='photo/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listings.realtor')),
            ],
        ),
    ]
